package dev.razafindratelo.misinformation.service.media;

import dev.razafindratelo.misinformation.model.classifier.FileType;
import jakarta.validation.ConstraintValidator;
import jakarta.validation.ConstraintValidatorContext;
import java.util.Set;
import org.springframework.stereotype.Component;
import org.springframework.web.multipart.MultipartFile;

@Component
public class MediaTypeValidator implements ConstraintValidator<ValidMediaType, MultipartFile> {

  private static final Set<String> VIDEO_TYPES =
      Set.of(
          "video/mp4",
          "video/webm",
          "video/ogg",
          "video/quicktime",
          "video/x-msvideo",
          "video/x-matroska",
          "video/mpeg",
          "video/avi",
          "video/flv",
          "video/x-flv",
          "video/x-m4v",
          "video/3gpp",
          "video/3gpp2",
          "video/x-ms-wmv",
          "video/vnd.dlna.mpeg-tts",
          "video/vnd.mpegurl",
          "video/x-f4v",
          "video/x-ms-asf",
          "video/x-ms-wvx",
          "video/x-ms-wm",
          "video/x-mng",
          "video/x-sgi-movie",
          "video/dv",
          "video/vnd.vivo");

  private static final Set<String> IMAGE_TYPES =
      Set.of(
          "image/jpeg",
          "image/png",
          "image/gif",
          "image/bmp",
          "image/webp",
          "image/tiff",
          "image/svg+xml",
          "image/heif",
          "image/heic",
          "image/heif-sequence",
          "image/heic-sequence",
          "image/avif",
          "image/jxl",
          "image/jp2",
          "image/jpx",
          "image/jpm",
          "image/vnd.microsoft.icon",
          "image/x-icon",
          "image/vnd.adobe.photoshop",
          "image/x-exr",
          "image/vnd.radiance",
          "image/x-canon-cr2",
          "image/x-canon-cr3",
          "image/x-sony-arw",
          "image/x-nikon-nef",
          "image/x-nikon-nrw",
          "image/x-fuji-raf",
          "image/x-olympus-orf",
          "image/x-panasonic-rw2",
          "image/x-pentax-pef",
          "image/x-samsung-srw",
          "image/x-kodak-kdc",
          "image/x-kodak-dcr",
          "image/x-leaf-mos",
          "image/x-mamiya-mef",
          "image/x-epson-erf",
          "image/x-sony-srf",
          "image/x-sony-sr2",
          "image/x-bayer-bay",
          "image/x-captureone-cs1",
          "image/x-phaseone-iiq",
          "image/x-phaseone-eip",
          "image/vnd.dxf",
          "image/vnd.dwg",
          "image/eps",
          "image/x-eps",
          "image/postscript",
          "image/x-tga",
          "image/x-targa",
          "image/x-portable-anymap",
          "image/x-portable-bitmap",
          "image/x-portable-graymap",
          "image/x-portable-pixmap",
          "image/x-cmu-raster",
          "image/x-xbitmap",
          "image/x-xpixmap",
          "image/x-xwindowdump",
          "image/vnd.djvu",
          "image/vnd.fpx",
          "image/vnd.fst",
          "image/vnd.fujixerox.edmics-mmr",
          "image/vnd.fujixerox.edmics-rlc",
          "image/vnd.ms-modi",
          "image/vnd.net-fpx",
          "image/vnd.wap.wbmp",
          "image/vnd.xiff");

  private static final Set<String> AUDIO_TYPES =
      Set.of(
          "audio/mpeg",
          "audio/mp3",
          "audio/mp4",
          "audio/x-m4a",
          "audio/aac",
          "audio/aacp",
          "audio/x-aac",
          "audio/ogg",
          "audio/opus",
          "audio/flac",
          "audio/x-flac",
          "audio/wav",
          "audio/x-wav",
          "audio/wave",
          "audio/x-pn-wav",
          "audio/webm",
          "audio/x-ms-wma",
          "audio/x-ms-wax",
          "audio/x-matroska",
          "audio/x-ms-asf",
          "audio/amr",
          "audio/amr-wb",
          "audio/amr-wb+",
          "audio/3gpp",
          "audio/3gpp2",
          "audio/x-mpegurl",
          "audio/x-scpls",
          "audio/midi",
          "audio/x-midi",
          "audio/sp-midi",
          "audio/rmf",
          "audio/x-rmf",
          "audio/x-aiff",
          "audio/aiff",
          "audio/x-pn-aiff",
          "audio/basic",
          "audio/x-basic",
          "audio/ulaw",
          "audio/x-alaw-basic",
          "audio/x-ms-wmv",
          "audio/x-realaudio",
          "audio/vnd.rn-realaudio",
          "audio/vnd.digital-winds",
          "audio/vnd.dts",
          "audio/vnd.dts.hd",
          "audio/vnd.lucent.voice",
          "audio/vnd.ms-playready.media.pya",
          "audio/vnd.nuera.ecelp4800",
          "audio/vnd.nuera.ecelp7470",
          "audio/vnd.nuera.ecelp9600",
          "audio/vnd.rip",
          "audio/x-ape",
          "audio/x-monkeys-audio",
          "audio/x-shorten",
          "audio/x-voc",
          "audio/x-vorbis+ogg",
          "audio/x-speex+ogg",
          "audio/x-tta",
          "audio/x-wavpack",
          "audio/x-wavpack-correction",
          "audio/x-xi",
          "audio/x-pn-realaudio",
          "audio/x-pn-realaudio-plugin",
          "audio/x-musepack",
          "audio/x-ms-shorten",
          "audio/x-stm",
          "audio/x-s3m",
          "audio/x-mod",
          "audio/x-it",
          "audio/x-xm",
          "audio/vorbis",
          "audio/vorbis-config",
          "audio/ac3",
          "audio/eac3",
          "audio/x-eac3",
          "audio/x-dsd",
          "audio/dsd",
          "audio/x-dff",
          "audio/x-mqa",
          "audio/x-mqa-flac",
          "audio/x-opus+ogg",
          "audio/ape",
          "audio/x-caf",
          "audio/x-mace",
          "audio/x-mpeg",
          "audio/x-ms-wvx",
          "audio/x-smd",
          "audio/x-svx",
          "audio/x-twinvq",
          "audio/x-twinvq-plugin",
          "audio/x-vnd.audioexplosion.mjuicemediafile",
          "audio/x-voxware",
          "audio/xm",
          "audio/it",
          "audio/s3m",
          "audio/mod",
          "audio/x-mo3",
          "audio/x-mtm",
          "audio/x-umx",
          "audio/x-sid",
          "audio/prs.sid",
          "audio/x-psf",
          "audio/x-psflib",
          "audio/x-psf2",
          "audio/x-psf2lib",
          "audio/x-ssf",
          "audio/x-ssflib",
          "audio/x-dsdiff",
          "audio/x-dsf",
          "audio/x-w64",
          "audio/x-rf64",
          "audio/x-mxf",
          "audio/mxf",
          "audio/tta",
          "audio/wavpack",
          "audio/x-ofr",
          "audio/x-optimfrog",
          "audio/x-shn",
          "audio/shn",
          "audio/x-ast",
          "audio/x-dts",
          "audio/x-dtshd",
          "audio/x-thd",
          "audio/x-true-hd",
          "audio/x-mlp",
          "audio/x-meridiana-lossless",
          "audio/x-adpcm",
          "audio/x-ima",
          "audio/x-ms-adpcm",
          "audio/x-g722",
          "audio/x-g723",
          "audio/x-g726",
          "audio/x-g728",
          "audio/x-g729",
          "audio/x-g729a",
          "audio/x-g729b",
          "audio/x-gsm",
          "audio/x-gsm-ms",
          "audio/x-qcelp",
          "audio/x-evrc",
          "audio/x-smv",
          "audio/x-vorbis",
          "audio/x-celt",
          "audio/x-speex",
          "audio/x-silk",
          "audio/x-ilbc",
          "audio/x-g719",
          "audio/x-g7221",
          "audio/x-siren",
          "audio/x-aptx",
          "audio/x-aptx-hd",
          "audio/x-ldac",
          "audio/x-sbc",
          "audio/x-he-aac",
          "audio/x-he-aac-v2",
          "audio/x-mp3",
          "audio/x-mp2",
          "audio/x-mp1",
          "audio/x-layer1",
          "audio/x-layer2",
          "audio/x-layer3");

  private FileType category;

  @Override
  public void initialize(ValidMediaType constraintAnnotation) {
    this.category = constraintAnnotation.value();
  }

  @Override
  public boolean isValid(MultipartFile file, ConstraintValidatorContext context) {
    if (file == null || file.isEmpty()) return false;

    String contentType = file.getContentType();
    if (contentType == null) return false;

    boolean isValid =
        switch (category) {
          case VIDEO -> VIDEO_TYPES.contains(contentType.toLowerCase());
          case IMAGE -> IMAGE_TYPES.contains(contentType.toLowerCase());
          case AUDIO -> AUDIO_TYPES.contains(contentType.toLowerCase());
        };

    if (!isValid) {
      context.disableDefaultConstraintViolation();
      context
          .buildConstraintViolationWithTemplate(
              String.format(
                  "File must be a valid %s type. Received: %s",
                  category.name().toLowerCase(), contentType))
          .addConstraintViolation();
    }

    return isValid;
  }
}
