package dev.razafindratelo.misinformation.model.classifier;

import java.util.Map;

public enum ContainerFormat {
  MP4,
  MP3,
  MKV,
  MOV,
  AVI,
  FLV,
  WMV,
  WEBM,
  MPEG_TS,
  MPEG_PS,
  THREEGP,
  OGG,
  M4A,
  WAV,
  FLAC,
  ASF,
  APE,
  AIFF,
  AAC,
  AC3,
  AMR,
  AU,
  DSD,
  DFF,
  DSF,
  MIDI,
  MID,
  OPUS,
  RA,
  RM,
  RMVB,
  VOB,
  F4V,
  M4V,
  M2TS,
  MTS,
  MXF,
  NUT,
  RMHD,
  SWF,
  THREEG2,
  THREEGA,
  WEBP,
  WMA,
  WTV,
  DIVX,
  XVID,
  HLS,
  DASH,
  ISMV,
  GP3,
  GP4,
  MKA,
  MKS,
  MK3D,
  OGV,
  OGA,
  SPX,
  CAF,
  MMF,
  AMV,
  YUV,
  Y4M,
  IVF,
  TS,
  PS,
  EVO,
  TP,
  TRP,
  M2P,
  MOD,
  TOD,
  MJPEG,
  MJ2,
  HEIF,
  HEIC,
  AVIF,
  BMP,
  GIF,
  JPEG,
  PNG,
  TIFF,
  WEBP_IMAGE,
  SVG,
  PDF,
  EPUB,
  MOBI,
  AZW,
  FB2,
  LRF,
  PDB,
  CBZ,
  CBR,
  CBT,
  CB7,
  DJVU,
  DJV,
  CHM,
  EXE,
  ISO,
  BIN,
  NRG,
  MDF,
  IMG,
  UNKNOWN;

  private static final Map<String, ContainerFormat> FORMAT_MAP =
      Map.ofEntries(
          Map.entry("MP4", MP4),
          Map.entry("MPEG-4", MP4),
          Map.entry("MPEG4", MP4),
          Map.entry("MKV", MKV),
          Map.entry("MATROSKA", MKV),
          Map.entry("MOV", MOV),
          Map.entry("QUICKTIME", MOV),
          Map.entry("AVI", AVI),
          Map.entry("FLV", FLV),
          Map.entry("WMV", WMV),
          Map.entry("ASF", ASF),
          Map.entry("WEBM", WEBM),
          Map.entry("MPEGTS", MPEG_TS),
          Map.entry("TS", TS),
          Map.entry("MPEG-TS", MPEG_TS),
          Map.entry("MPEGPS", MPEG_PS),
          Map.entry("PS", PS),
          Map.entry("MPEG-PS", MPEG_PS),
          Map.entry("MP3", MP3),
          Map.entry("MPEG", MP3),
          Map.entry("MPEG1LAYER3", MP3),
          Map.entry("3GP", THREEGP),
          Map.entry("THREEGP", THREEGP),
          Map.entry("OGG", OGG),
          Map.entry("M4A", M4A),
          Map.entry("WAV", WAV),
          Map.entry("FLAC", FLAC),
          Map.entry("AIFF", AIFF),
          Map.entry("APE", APE),
          Map.entry("AAC", AAC),
          Map.entry("AC3", AC3),
          Map.entry("AMR", AMR),
          Map.entry("AU", AU),
          Map.entry("DSD", DSD),
          Map.entry("DFF", DFF),
          Map.entry("DSF", DSF),
          Map.entry("MIDI", MIDI),
          Map.entry("MID", MID),
          Map.entry("OPUS", OPUS),
          Map.entry("RA", RA),
          Map.entry("RM", RM),
          Map.entry("RMVB", RMVB),
          Map.entry("VOB", VOB),
          Map.entry("F4V", F4V),
          Map.entry("M4V", M4V),
          Map.entry("M2TS", M2TS),
          Map.entry("MTS", MTS),
          Map.entry("MXF", MXF),
          Map.entry("NUT", NUT),
          Map.entry("RMHD", RMHD),
          Map.entry("SWF", SWF),
          Map.entry("3G2", THREEG2),
          Map.entry("THREEG2", THREEG2),
          Map.entry("3GA", THREEGA),
          Map.entry("THREEGA", THREEGA),
          Map.entry("WMA", WMA),
          Map.entry("WTV", WTV),
          Map.entry("DIVX", DIVX),
          Map.entry("XVID", XVID),
          Map.entry("HLS", HLS),
          Map.entry("DASH", DASH),
          Map.entry("ISMV", ISMV),
          Map.entry("GP3", GP3),
          Map.entry("GP4", GP4),
          Map.entry("MKA", MKA),
          Map.entry("MKS", MKS),
          Map.entry("MK3D", MK3D),
          Map.entry("OGV", OGV),
          Map.entry("OGA", OGA),
          Map.entry("SPX", SPX),
          Map.entry("CAF", CAF),
          Map.entry("MMF", MMF),
          Map.entry("AMV", AMV),
          Map.entry("YUV", YUV),
          Map.entry("Y4M", Y4M),
          Map.entry("IVF", IVF),
          Map.entry("EVO", EVO),
          Map.entry("TP", TP),
          Map.entry("TRP", TRP),
          Map.entry("M2P", M2P),
          Map.entry("MOD", MOD),
          Map.entry("TOD", TOD),
          Map.entry("MJPEG", MJPEG),
          Map.entry("MJ2", MJ2),
          Map.entry("HEIF", HEIF),
          Map.entry("HEIC", HEIC),
          Map.entry("AVIF", AVIF),
          Map.entry("BMP", BMP),
          Map.entry("GIF", GIF),
          Map.entry("JPEG", JPEG),
          Map.entry("JPG", JPEG),
          Map.entry("PNG", PNG),
          Map.entry("TIFF", TIFF),
          Map.entry("TIF", TIFF),
          Map.entry("WEBP", WEBP_IMAGE),
          Map.entry("SVG", SVG),
          Map.entry("PDF", PDF),
          Map.entry("EPUB", EPUB),
          Map.entry("MOBI", MOBI),
          Map.entry("AZW", AZW),
          Map.entry("FB2", FB2),
          Map.entry("LRF", LRF),
          Map.entry("PDB", PDB),
          Map.entry("CBZ", CBZ),
          Map.entry("CBR", CBR),
          Map.entry("CBT", CBT),
          Map.entry("CB7", CB7),
          Map.entry("DJVU", DJVU),
          Map.entry("DJV", DJV),
          Map.entry("CHM", CHM),
          Map.entry("EXE", EXE),
          Map.entry("ISO", ISO),
          Map.entry("BIN", BIN),
          Map.entry("NRG", NRG),
          Map.entry("MDF", MDF),
          Map.entry("IMG", IMG));

  public static ContainerFormat fromString(String value) {
    if (value == null) return UNKNOWN;

    for (String token : value.trim().split(",")) {
      String normalized = token.trim().toUpperCase();
      ContainerFormat format = FORMAT_MAP.get(normalized);
      if (format != null) return format;
    }

    return UNKNOWN;
  }
}
